# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.zone_ranges import ZoneRanges  # noqa: F401,E501


class HeartRateZoneRanges(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'custom_zones': 'bool',
        'zones': 'ZoneRanges'
    }

    attribute_map = {
        'custom_zones': 'custom_zones',
        'zones': 'zones'
    }

    def __init__(self, custom_zones=None, zones=None):  # noqa: E501
        """HeartRateZoneRanges - a model defined in Swagger"""  # noqa: E501

        self._custom_zones = None
        self._zones = None
        self.discriminator = None

        if custom_zones is not None:
            self.custom_zones = custom_zones
        if zones is not None:
            self.zones = zones

    @property
    def custom_zones(self):
        """Gets the custom_zones of this HeartRateZoneRanges.  # noqa: E501

        Whether the athlete has set their own custom heart rate zones  # noqa: E501

        :return: The custom_zones of this HeartRateZoneRanges.  # noqa: E501
        :rtype: bool
        """
        return self._custom_zones

    @custom_zones.setter
    def custom_zones(self, custom_zones):
        """Sets the custom_zones of this HeartRateZoneRanges.

        Whether the athlete has set their own custom heart rate zones  # noqa: E501

        :param custom_zones: The custom_zones of this HeartRateZoneRanges.  # noqa: E501
        :type: bool
        """

        self._custom_zones = custom_zones

    @property
    def zones(self):
        """Gets the zones of this HeartRateZoneRanges.  # noqa: E501


        :return: The zones of this HeartRateZoneRanges.  # noqa: E501
        :rtype: ZoneRanges
        """
        return self._zones

    @zones.setter
    def zones(self, zones):
        """Sets the zones of this HeartRateZoneRanges.


        :param zones: The zones of this HeartRateZoneRanges.  # noqa: E501
        :type: ZoneRanges
        """

        self._zones = zones

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HeartRateZoneRanges, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HeartRateZoneRanges):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
