# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cadence_stream import CadenceStream  # noqa: E501
from swagger_client.rest import ApiException


class TestCadenceStream(unittest.TestCase):
    """CadenceStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCadenceStream(self):
        """Test CadenceStream"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cadence_stream.CadenceStream()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
