# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.gears_api import GearsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGearsApi(unittest.TestCase):
    """GearsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.gears_api.GearsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_gear_by_id(self):
        """Test case for get_gear_by_id

        Get Equipment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
