# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.streams_api import StreamsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStreamsApi(unittest.TestCase):
    """StreamsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.streams_api.StreamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_activity_streams(self):
        """Test case for get_activity_streams

        Get Activity Streams  # noqa: E501
        """
        pass

    def test_get_segment_effort_streams(self):
        """Test case for get_segment_effort_streams

        Get segment effort streams  # noqa: E501
        """
        pass

    def test_get_segment_streams(self):
        """Test case for get_segment_streams

        Get Segment Streams  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
