# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.uploads_api import UploadsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUploadsApi(unittest.TestCase):
    """UploadsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.uploads_api.UploadsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_upload(self):
        """Test case for create_upload

        Upload Activity  # noqa: E501
        """
        pass

    def test_get_upload_by_id(self):
        """Test case for get_upload_by_id

        Get Upload  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
