# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.summary_segment_effort import SummarySegmentEffort  # noqa: E501
from swagger_client.rest import ApiException


class TestSummarySegmentEffort(unittest.TestCase):
    """SummarySegmentEffort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSummarySegmentEffort(self):
        """Test SummarySegmentEffort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.summary_segment_effort.SummarySegmentEffort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
